apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app22
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/javanshir301/gitops-apps.git
    targetRevision: HEAD
    path: base/app22
    helm:
      values: |
        # istəsən burda helm chartdakı values-ları override edə bilərsən
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

